version: "3.9"

services:
  nginx-manager:
    build: .
    container_name: nginx-manager
    privileged: true  # Нужно для systemctl
    volumes:
      - /var/run/dbus:/var/run/dbus
    ports:
      - "8000:8000"
    network_mode: bridge
